/**
 * Regenerates `tests/fixtures/group-crypto-vectors.json`.
 *
 *   npx ts-node --project tests/tsconfig.json scripts/generate-group-crypto-vectors.ts
 *
 * Every input is hardcoded, so the output is byte-identical on every run — a diff in the
 * fixture means the envelope format changed, which is the signal we want. After regenerating,
 * copy the fixture to `track-me-android/app/src/test/resources/` (and iOS later) and re-run
 * their vector tests: they are the only thing standing between us and a silent
 * "the feature doesn't work" cross-platform mismatch (SCOPE §5.3).
 */

import fs from 'fs';
import path from 'path';
import {
  CryptoVectorCase,
  CryptoVectorFile,
  ENVELOPE_VERSION,
  EnvelopePurpose,
  HKDF_INFO,
  KEY_LENGTH_BYTES,
  deriveGroupKey,
  envelopeContext,
  groupTokenHash,
  seal,
} from '../lib/group/crypto';

interface Spec {
  name: string;
  token: string;
  purpose: EnvelopePurpose;
  memberUid: string | null;
  plaintext: string;
  nonceHex: string;
}

// Tokens are real-shaped (22 base64url chars) but fixed, never random.
const TOKEN_A = 'Zm9vYmFyYmF6cXV4MTIzNA';
const TOKEN_B = '9tK-3xQzR1sV7wY0aB2cD4';

const SPECS: Spec[] = [
  {
    name: 'group metadata envelope',
    token: TOKEN_A,
    purpose: 'meta',
    memberUid: null,
    plaintext: JSON.stringify({ name: "Sunday Riders", ownerDisplayName: "Priya" }),
    nonceHex: '000102030405060708090a0b',
  },
  {
    name: 'roster entry envelope',
    token: TOKEN_A,
    purpose: 'roster',
    memberUid: 'uid-alice',
    plaintext: JSON.stringify({ displayName: 'Alice Kaur', initials: 'AK', photoUrl: null }),
    nonceHex: '0b0a090807060504030201ff',
  },
  {
    name: 'position envelope',
    token: TOKEN_A,
    purpose: 'pos',
    memberUid: 'uid-alice',
    plaintext: JSON.stringify({ lat: 12.9716, lng: 77.5946, spd: 4.2, hdg: 137, bat: 82, moving: true }),
    nonceHex: 'ffeeddccbbaa998877665544',
  },
  {
    name: 'position envelope, different member, same group',
    token: TOKEN_A,
    purpose: 'pos',
    memberUid: 'uid-bob',
    plaintext: JSON.stringify({ lat: 12.98, lng: 77.6, spd: 0, hdg: null, bat: 40, moving: false }),
    nonceHex: '112233445566778899aabbcc',
  },
  {
    // Non-ASCII in a group name is the most likely place a port gets its string encoding
    // wrong, and the failure is silent: a mismatched byte count still decrypts to *something*
    // on the sealing platform. 7 locales ship in 1.7.x, so this is not a hypothetical.
    name: 'unicode metadata (UTF-8 encoding check)',
    token: TOKEN_B,
    purpose: 'meta',
    memberUid: null,
    plaintext: JSON.stringify({ name: 'रविवार की सवारी 🚴‍♀️ 日曜日', ownerDisplayName: 'Ravi' }),
    nonceHex: 'cafebabe0123456789abcdef',
  },
  {
    name: 'empty plaintext',
    token: TOKEN_B,
    purpose: 'meta',
    memberUid: null,
    plaintext: '',
    nonceHex: '000000000000000000000000',
  },
];

function build(spec: Spec): CryptoVectorCase {
  const key = deriveGroupKey(spec.token);
  const context = envelopeContext(spec.purpose, spec.memberUid ?? undefined);
  const nonce = Buffer.from(spec.nonceHex, 'hex');

  return {
    name: spec.name,
    token: spec.token,
    tokenHashHex: groupTokenHash(spec.token),
    keyHex: key.toString('hex'),
    purpose: spec.purpose,
    memberUid: spec.memberUid,
    context,
    plaintext: spec.plaintext,
    nonceB64Url: nonce.toString('base64url'),
    envelope: seal(key, spec.plaintext, context, nonce),
  };
}

const fixture: CryptoVectorFile = {
  version: ENVELOPE_VERSION,
  note:
    'Shared Group Ride crypto test vectors. Generated by scripts/generate-group-crypto-vectors.ts — '
    + 'do not hand-edit. Copied verbatim into every client repo; all platforms must reproduce '
    + 'keyHex and envelope exactly from token + plaintext + context + nonce.',
  hkdf: { info: HKDF_INFO, keyLengthBytes: KEY_LENGTH_BYTES, saltIsEmpty: true },
  cases: SPECS.map(build),
};

const target = path.join(__dirname, '..', 'tests', 'fixtures', 'group-crypto-vectors.json');
fs.mkdirSync(path.dirname(target), { recursive: true });
fs.writeFileSync(target, JSON.stringify(fixture, null, 2) + '\n', 'utf8');
process.stdout.write(`wrote ${fixture.cases.length} vectors to ${path.relative(process.cwd(), target)}\n`);
